sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
- COMMIT=${TRAVIS_COMMIT::8}
# stylecheck, compile unit-test and build
- mvn package
# docker build and upload
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- export REPO=vinaysen88/trace-producer-svc
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
