version: "2"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet
  trace-producer-svc:
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: